[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

# 간단한 API 테스트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple/:splat"
  status = 200

# SPA를 위한 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
