[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

# API 요청을 위한 리다이렉트 (가장 위에 위치시키고 force=true 추가)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/*" 
  status = 200
  force = true

# SPA를 위한 리다이렉트 (catch-all)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"