[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

# GenAI 테스트 함수
[[redirects]]
  from = "/api/genai-test"
  to = "/.netlify/functions/genai-test"
  status = 200

# 기존 Express API (원래 버전)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA를 위한 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
