[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

# 개별 함수들에 대한 리다이렉트
[[redirects]]
  from = "/api/msds/chemlist"
  to = "/.netlify/functions/msds-chemlist"
  status = 200
  force = true

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/api/env-check"
  to = "/.netlify/functions/env-check"
  status = 200
  force = true

# 기존 Express API에 대한 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA를 위한 리다이렉트 (catch-all)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
